### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Sylensky** [comment]
Thanks for the PR. The language translations usually are handled over weblates third party resources over namelessmc which then create a pull request with all changes in languages.
Could you change that?
Aside from that looks good to me!

**Comment by Justman10000** [comment]
@PadowYT2 @Sylensky

Fixed

**Comment by Sylensky** [comment]
Squash or even better create a fixup commit to reduce commit overhead.

**Comment by Justman10000** [comment]
> Squash or even better create a fixup commit to reduce commit overhead.

?

**Comment by Sylensky** [comment]
The [d2b0d72](https://github.com/VertisanPRO/Badges/pull/6/commits/d2b0d72e232760688b8f6466d1e0caeeec650bdd) and the [7a86870](https://github.com/VertisanPRO/Badges/pull/6/commits/7a868709f01d478e9145d6354b7a1a467889d6d6) should be removed and [1367eb9](https://github.com/VertisanPRO/Badges/pull/6/commits/1367eb9c77868b62d98c8770ed77a3e79e2ebcd7) can be squashed (combined with) this [5d3264b](https://github.com/VertisanPRO/Badges/pull/6/commits/5d3264bb1695149a1ec6ba65ef7131fab08cb706) commit.

You may have a look at these particular git features:
https://blog.git-init.com/how-to-tidy-up-a-dirty-commit-history/#:~:text=The%20difference%20between%20squash%20and,starts%20the%20interactive%20rebase%20process.

**Comment by Justman10000** [comment]
> The [d2b0d72](https://github.com/VertisanPRO/Badges/pull/6/commits/d2b0d72e232760688b8f6466d1e0caeeec650bdd) and the [7a86870](https://github.com/VertisanPRO/Badges/pull/6/commits/7a868709f01d478e9145d6354b7a1a467889d6d6) should be removed and [1367eb9](https://github.com/VertisanPRO/Badges/pull/6/commits/1367eb9c77868b62d98c8770ed77a3e79e2ebcd7) can be squashed (combined with) this [5d3264b](https://github.com/VertisanPRO/Badges/pull/6/commits/5d3264bb1695149a1ec6ba65ef7131fab08cb706) commit.
> 
> You may have a look at these particular git features: https://blog.git-init.com/how-to-tidy-up-a-dirty-commit-history/#:~:text=The%20difference%20between%20squash%20and,starts%20the%20interactive%20rebase%20process.

I don't get it! One cannot delete or merge commits?

**Comment by Sylensky** [comment]
Check out the link i provided together with the keyword of `git rebase`.

**Comment by Justman10000** [comment]
> Check out the link i provided together with the keyword of `git rebase`.

Yes, but only applies to the last commit

**Comment by Sylensky** [comment]
If you run it `non interactively` yes. You can do much more and edit commit by commit if you add `-i` to your command.

**Comment by Justman10000** [comment]
> If you run it `non interactively` yes. You can do much more and edit commit by commit if you add `-i` to your command.

It doesn't matter! With the merge all commits are merged to one anyway

**Comment by Sylensky** [comment]
git does not work that way as you see here:
image

Ill let this pass anyway sicne iam happy with the contribution.

**Pull request merged**
